<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>RestKit.IntegrationTests</RootNamespace>
    <AssemblyName>RestKit.IntegrationTests</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <WarningLevel>4</WarningLevel>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RestKit.TestLib\RestKit.TestLib.csproj" />
    <ProjectReference Include="..\RestKit\RestKit.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.3.3" />
    <PackageReference Include="MSTest.TestFramework" Version="4.3.3" />
  </ItemGroup>

</Project>
